name: publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GIT_PASSWORD }}
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: 'Installing GitBook CLI'
      run: npm install -g gitbook-cli
    - name: 'Generating Bengal Message Book'
      run: |
        gitbook install
        gitbook build
        git clone https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PASSWORD }}@github.com/manorrock/bengal-website
        cd bengal-website
        git checkout gh-pages
        mkdir -p message/book || true
        cd message/book
        rm -rf *
        mv ../../../_book/* .
        ls 
        git config user.email "noreply@manorrock.com"
        git config user.name "Automated process"
        git add .
        git commit -m "Publishing Bengal Message Book"
        git push
